# ./exports.conf
# this file should export the bind mounted directories from the docker-compose.yml file.


/exports/www *(rw,sync,no_subtree_check)
/exports/sync *(rw,sync,no_subtree_check,no_root_squash)